### ISSUE TITLE
How to achieve baseline

### ISSUE THREAD

**Issue by ChinaYiqun** [cvl-umass/semi-inat-2020#1]
Dear organizer, thanks  for your hosting this competition and creating a good communication opportunity for us.May I ask you the detail parameters of Adam you used and how many GPUs you used to achineve your baseline?I tried for a long time, but I couldn't reach it

**Comment by jongchyisu** [comment]
Hi, I am only using 1 GPU and a batch size of 32 to get the baseline performance. I believe it is not hard to achieve since on the leaderboard most of the teams are way better than my baseline.
