### ISSUE TITLE
The 'categories' in anno_val.json is wrong?

### ISSUE THREAD

**Issue by linzhiqiu** [cvl-umass/semi-inat-2020#2]
Because this is supposed to be Aves classification, I checked out the annotation in val set for the 'categories' field, and see many taxa of Insecta, e.g.: {'kingdom': 'Animalia', 'name': 'Paranapiacaba tricincta', 'family': 'Chrysomelidae', 'supercategory': 'Insecta', 'phylum': 'Arthropoda', 'id': 0, 'order': 'Coleoptera', 'genus': 'Paranapiacaba', 'class': 'Insecta'}..

I wanted to know whether there is something wrong with the annotations?

Where can I locate the label corresponding to the original inat challenge?

**Comment by jongchyisu** [comment]
Thanks for pointing this out. We do not intend to release the species names and the taxonomy. The 'categories' in anno_val.json are also wrong and should be ignored. Please disregard this and I have updated the annotation files. Thank you!
